repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 --ignore=W503
        pass_filenames: false
        always_run: true
        language: system
        types: [python]
        stages: [commit]
      - id: pytest
        name: pytest
        entry: pytest tests
        pass_filenames: false
        always_run: true
        language: system
        types: [python]
        stages: [push]